package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.event.ActionEvent;
import javafx.scene.Parent;
import javafx.scene.control.Menu;

public class RootLayoutController {
	@FXML
	private Menu menuCerrarSesion;

	// Event Listener on Menu[#menuCerrarSesion].onAction
	@FXML
	public void cerrarSesion(ActionEvent event) {
		// TODO Autogenerated
		/*Parent root = FXMLLoader.load(getClass().getResource("Login.fxml"));
		Stage stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		Scene scene = new Scene(root);
		stage.setScene(scene);*/
	}
}
